export const routeNames: Record<string, string> = {
  '/': 'Inicio',
  '/dashboard': 'Dashboard',
  '/products': 'Productos',
  '/inventory': 'Inventario',
  '/sales': 'Ventas',
  '/purchases': 'Compras',
  '/customers': 'Clientes',
  '/suppliers': 'Proveedores',
  '/categories': 'Categorías',
  '/categories/create': 'Crear',
  '/inventory-movements': 'Movimientos de Inventario',
  '/wastes': 'Mermas',
  '/reports': 'Reportes',
  '/reports/sales': 'Reportes de Ventas',
  '/reports/inventory': 'Reportes de Inventario',
  '/reports/purchases': 'Reportes de Compras',
  '/settings': 'Configuración',
  '/help': 'Ayuda',
  '/search': 'Buscar',
  '/database': 'Base de Datos',
  '/analytics': 'Analytics',
  '/account': 'Perfil',
};
